version: '3'

services:
  redis:
    container_name: repd_redis
    image: redis:3.2
    ports:
      - "6379:6379"

  repd:
    container_name: repd_app
    image: repd:build
    build:
      context: ../.
    environment:
      - REPD_TEST_REDISADDR=redis:6379
    links:
      - redis
    ports:
      - "8080:8080"
